name: OPPotions
version: 1.3
author: Haaris Iqbal (Volcifire)
main: com.haarisiqbal.oppotions.Main
description: New special potions in the game, dropped by hostile mobs, that have very powerful effects / events.